### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by tomsommer**

### CODE REVIEW

**Review by mustramit — APPROVED** [review]

**Comment by acasademont** [comment]
Is this something still needed? Sorry for totally missing this PR

**Comment by tomsommer** [comment]
Yes. Very much need it :)

**Comment by acasademont** [comment]
@tomsommer I suggest adding a ">=7" in composer instead of adding now php 8 as this will break again with php 9. Can you do that?

And tbh, I don't know about Travis these days, is this still working well?

**Comment by tomsommer** [comment]
Done

**Comment by tomsommer** [comment]
@acasademont please merge :)

**Comment by acasademont** [comment]
Done!! Thanks for the fix :)

**Comment by tomsommer** [comment]
@acasademont Can you also make sure https://packagist.org/packages/ulabox/nif-validator is updated? It doesn't auto-update

**Comment by acasademont** [comment]
Should be working now, can you retry?

**Comment by tomsommer** [comment]
Works. Thank you!

**Pull request merged**
